### ISSUE TITLE
Makefile:25: recipe for target 'compose-db-create' failed

### ISSUE THREAD

**Issue by ilyar** [hexlet-codebattle/codebattle#45]
```bash
git clone https://github.com/hexlet-codebattle/codebattle.git 
cd codebattle 
make development-build-local 
make compose-setup 

...log ok...

All dependencies up to date
docker-compose run web mix compile
Starting db ... done
docker-compose run web mix ecto.create
Starting db ... done
** (Mix) The database for Codebattle.Repo couldn't be created: FATAL 28P01 (invalid_password): password authentication failed for user "postgres"

08:39:28.277 [error] GenServer #PID<0.210.0> terminating
** (Postgrex.Error) FATAL 28P01 (invalid_password): password authentication failed for user "postgres"
    (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
Makefile:25: recipe for target 'compose-db-create' failed
make: *** [compose-db-create] Error 1
```

Предполагаю это локальная проблема, в любом случае будут полезны предположения по решению.

**Comment by antonshwab** [comment]
У меня такое же.

**Comment by ilyar** [comment]
Решил, чисткой томов:

    docker volume prune
