### ISSUE TITLE
Локально тесты не прошли. и ошибка compose.

### ISSUE THREAD

**Issue by krivtsov** [hexlet-codebattle/codebattle#47]
Репозиторий клонированный, без изменений

```
mix test

18:01:55.538 [error] GenServer #PID<0.209.0> terminating
** (KeyError) key :hostname not found in: [types: Postgrex.DefaultTypes, backoff_type: :stop, pool: DBConnection.Connection, database: "
template1", otp_app: :codebattle, repo: Codebattle.Repo, adapter: Ecto.Adapters.Postgres]
    (elixir) lib/keyword.ex:371: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:54: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil

** (Mix) The database for Codebattle.Repo couldn't be created: an exception was raised:
    ** (KeyError) key :hostname not found in: [types: Postgrex.DefaultTypes, backoff_type: :stop, pool: DBConnection.Connection, databas
e: "template1", otp_app: :codebattle, repo: Codebattle.Repo, adapter: Ecto.Adapters.Postgres]
        (elixir) lib/keyword.ex:371: Keyword.fetch!/2
        (postgrex) lib/postgrex/protocol.ex:54: Postgrex.Protocol.connect/1
        (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Makefile:48: recipe for target 'test' failed
make: *** [test] Error 1
```

и ошибка compose-setup 

```
docker-compose build web
Building web
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Makefile:12: recipe for target 'compose-build' failed
make: *** [compose-build] Error 1
```

**Comment by imamatory** [comment]
Это твоя локальная ошибка. Думаю это поможет https://github.com/docker/compose/issues/1214#issuecomment-102246925

**Comment by krivtsov** [comment]
```docker-compose run --rm web mix deps.get
Starting db ... 
Starting db ... error

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint db (9c5edcbb3b287bd26d7301efe2e0254a4f2b783aeab0b33973e0edf7c57a9538): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
```

решение это проблемы 
`service postgresql stop`

**Comment by PeresvetS** [comment]
Если и это вдруг кому-то не поможет, что можно просто и резко написать `sudo killall postgres`

**Comment by krivtsov** [comment]
а есть в этом файле  `codebattle/deps/ecto/lib/ecto/adapters/postgres.ex`
запись  `template1`

```  def storage_up(opts) do
    database = Keyword.fetch!(opts, :database) || raise ":database is nil in repository configuration"
    encoding = opts[:encoding] || "UTF8"
    opts     = Keyword.put(opts, :database, "**template1**")```
```def storage_down(opts) do
    database = Keyword.fetch!(opts, :database) || raise ":database is nil in repository configuration"
    command  = "DROP DATABASE \"#{database}\""
    opts     = Keyword.put(opts, :database, "**template1**")```

**Comment by PeresvetS** [comment]
Теперь всё должно полностью работать. 
Если вдруг у кого-то появляется ещё какая-то ошибка, то, пожалуйста, создайте новый issue с её описанием.
